AWSTemplateFormatVersion: '2010-09-09'
Description: 'Application Load Balancer with Blue/Green target groups'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    AllowedValues:
      - staging
      - production
    Default: staging

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 1 ID

  PublicSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 2 ID

  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ALB Security Group ID

  CertificateArn:
    Type: String
    Description: ACM certificate ARN for HTTPS
    Default: ''

  DomainName:
    Type: String
    Description: Domain name for this environment
    Default: ''

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub 'isms-${Environment}-alb'
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub 'isms-${Environment}-alb'
        - Key: Environment
          Value: !Ref Environment

  BackendTargetGroupBlue:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub 'isms-${Environment}-backend-blue'
      Port: 4000
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /api/health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Tags:
        - Key: Name
          Value: !Sub 'isms-${Environment}-backend-blue'
        - Key: Environment
          Value: !Ref Environment
        - Key: Color
          Value: blue

  BackendTargetGroupGreen:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub 'isms-${Environment}-backend-green'
      Port: 4000
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /api/health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Tags:
        - Key: Name
          Value: !Sub 'isms-${Environment}-backend-green'
        - Key: Environment
          Value: !Ref Environment
        - Key: Color
          Value: green

  FrontendTargetGroupBlue:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub 'isms-${Environment}-frontend-blue'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Tags:
        - Key: Name
          Value: !Sub 'isms-${Environment}-frontend-blue'
        - Key: Environment
          Value: !Ref Environment
        - Key: Color
          Value: blue

  FrontendTargetGroupGreen:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub 'isms-${Environment}-frontend-green'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Tags:
        - Key: Name
          Value: !Sub 'isms-${Environment}-frontend-green'
        - Key: Environment
          Value: !Ref Environment
        - Key: Color
          Value: green

  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions: !If
        - HasCertificate
        - - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: 443
              StatusCode: HTTP_301
        - - Type: forward
            ForwardConfig:
              TargetGroups:
                - TargetGroupArn: !Ref FrontendTargetGroupBlue
                  Weight: 100

  HTTPBackendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: NoCertificate
    Properties:
      ListenerArn: !Ref HTTPListener
      Priority: 100
      Conditions:
        - Field: path-pattern
          Values:
            - '/api/*'
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref BackendTargetGroupBlue
                Weight: 100

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: HasCertificate
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref CertificateArn
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref FrontendTargetGroupBlue
                Weight: 100

  BackendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HasCertificate
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 100
      Conditions:
        - Field: path-pattern
          Values:
            - '/api/*'
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref BackendTargetGroupBlue
                Weight: 100

  FrontendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HasCertificate
    Properties:
      ListenerArn: !Ref HTTPSListener
      Priority: 200
      Conditions:
        - Field: path-pattern
          Values:
            - '/*'
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref FrontendTargetGroupBlue
                Weight: 100

Conditions:
  HasCertificate: !Not [!Equals [!Ref CertificateArn, '']]
  NoCertificate: !Equals [!Ref CertificateArn, '']

Outputs:
  LoadBalancerArn:
    Description: Application Load Balancer ARN
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub '${AWS::StackName}-LoadBalancerArn'

  LoadBalancerDNSName:
    Description: Application Load Balancer DNS name
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub '${AWS::StackName}-LoadBalancerDNSName'

  BackendTargetGroupBlueArn:
    Description: Backend Blue Target Group ARN
    Value: !Ref BackendTargetGroupBlue
    Export:
      Name: !Sub '${AWS::StackName}-BackendTargetGroupBlueArn'

  BackendTargetGroupGreenArn:
    Description: Backend Green Target Group ARN
    Value: !Ref BackendTargetGroupGreen
    Export:
      Name: !Sub '${AWS::StackName}-BackendTargetGroupGreenArn'

  FrontendTargetGroupBlueArn:
    Description: Frontend Blue Target Group ARN
    Value: !Ref FrontendTargetGroupBlue
    Export:
      Name: !Sub '${AWS::StackName}-FrontendTargetGroupBlueArn'

  FrontendTargetGroupGreenArn:
    Description: Frontend Green Target Group ARN
    Value: !Ref FrontendTargetGroupGreen
    Export:
      Name: !Sub '${AWS::StackName}-FrontendTargetGroupGreenArn'

  LoadBalancerListenerArn:
    Description: ALB Listener ARN (HTTP or HTTPS depending on certificate)
    Value: !If
      - HasCertificate
      - !Ref HTTPSListener
      - !Ref HTTPListener
    Export:
      Name: !Sub '${AWS::StackName}-LoadBalancerListenerArn'

