AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECR repositories with lifecycle policies'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    AllowedValues:
      - staging
      - production
    Default: staging

Resources:
  BackendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: isms-backend
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images tagged with staging or production",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["staging", "production"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 2,
                "description": "Keep last 5 images tagged with commit SHA",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["sha-"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 3,
                "description": "Expire untagged images after 7 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 4,
                "description": "Expire images older than 30 days (except tagged)",
                "selection": {
                  "tagStatus": "any",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: isms-backend
        - Key: Environment
          Value: !Ref Environment

  FrontendRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: isms-frontend
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images tagged with staging or production",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["staging", "production"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 2,
                "description": "Keep last 5 images tagged with commit SHA",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["sha-"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 3,
                "description": "Expire untagged images after 7 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 4,
                "description": "Expire images older than 30 days (except tagged)",
                "selection": {
                  "tagStatus": "any",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: isms-frontend
        - Key: Environment
          Value: !Ref Environment

Outputs:
  BackendRepositoryUri:
    Description: Backend ECR repository URI
    Value: !GetAtt BackendRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-BackendRepositoryUri'

  FrontendRepositoryUri:
    Description: Frontend ECR repository URI
    Value: !GetAtt FrontendRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-FrontendRepositoryUri'

  BackendRepositoryArn:
    Description: Backend ECR repository ARN
    Value: !GetAtt BackendRepository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BackendRepositoryArn'

  FrontendRepositoryArn:
    Description: Frontend ECR repository ARN
    Value: !GetAtt FrontendRepository.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FrontendRepositoryArn'

  DocumentServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: isms-document-service
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images tagged with staging or production",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["staging", "production"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 2,
                "description": "Expire untagged images after 7 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: isms-document-service
        - Key: Environment
          Value: !Ref Environment

  AIServiceRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: isms-ai-service
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: !Sub |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 images tagged with staging or production",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["staging", "production"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": {
                  "type": "expire"
                }
              },
              {
                "rulePriority": 2,
                "description": "Expire untagged images after 7 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: isms-ai-service
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DocumentServiceRepositoryUri:
    Description: Document Service ECR repository URI
    Value: !GetAtt DocumentServiceRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-DocumentServiceRepositoryUri'

  AIServiceRepositoryUri:
    Description: AI Service ECR repository URI
    Value: !GetAtt AIServiceRepository.RepositoryUri
    Export:
      Name: !Sub '${AWS::StackName}-AIServiceRepositoryUri'



