AWSTemplateFormatVersion: '2010-09-09'
Transform:
  - AWS::CodeDeployBlueGreen
Description: 'Main CloudFormation template orchestrating all ISMS infrastructure resources'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    AllowedValues:
      - staging
      - production
    Default: staging

  AwsAccountId:
    Type: String
    Description: AWS Account ID where resources will be created
    AllowedPattern: '^[0-9]{12}$'

  DomainName:
    Type: String
    Description: Domain name for this environment
    Default: ''

  CertificateArn:
    Type: String
    Description: ACM certificate ARN for HTTPS (leave empty to create manually)
    Default: ''

  VpcCidr:
    Type: String
    Description: CIDR block for VPC
    Default: 10.0.0.0/16

  BackendImageTag:
    Type: String
    Description: Backend Docker image tag
    Default: staging

  FrontendImageTag:
    Type: String
    Description: Frontend Docker image tag
    Default: staging

  AuroraMinCapacity:
    Type: Number
    Description: Minimum Aurora Capacity Units (ACU)
    Default: 0.5
    MinValue: 0.5
    MaxValue: 128

  AuroraMaxCapacity:
    Type: Number
    Description: Maximum Aurora Capacity Units (ACU)
    Default: 16
    MinValue: 0.5
    MaxValue: 128

  MinTaskCount:
    Type: Number
    Description: Minimum number of tasks
    Default: 1
    MinValue: 1

  MaxTaskCount:
    Type: Number
    Description: Maximum number of tasks
    Default: 4
    MinValue: 1

  UseFargateSpot:
    Type: String
    Description: Use Fargate Spot capacity provider
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

  SpotPercentage:
    Type: Number
    Description: Percentage of tasks to run on Spot
    Default: 70
    MinValue: 0
    MaxValue: 100

  UseGraviton2:
    Type: String
    Description: Use ARM64 (Graviton2) architecture
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'

  DeploymentType:
    Type: String
    Description: Deployment type (canary or linear)
    AllowedValues:
      - canary
      - linear
    Default: canary

  TrafficShiftPercentage:
    Type: Number
    Description: Initial traffic shift percentage
    Default: 10
    MinValue: 1
    MaxValue: 100

  GitHubOrg:
    Type: String
    Description: GitHub organization name (optional, for OIDC)
    Default: ''

  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: 'ISMS-Documentation'

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        Environment: !Ref Environment
        VpcCidr: !Ref VpcCidr

  SecretsManagerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./secrets-manager.yaml
      Parameters:
        Environment: !Ref Environment

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: ./security-groups.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId

  AuroraStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityGroupsStack
      - SecretsManagerStack
    Properties:
      TemplateURL: ./aurora.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        AuroraSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.AuroraSecurityGroupId
        AuroraMinCapacity: !Ref AuroraMinCapacity
        AuroraMaxCapacity: !Ref AuroraMaxCapacity

  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam-roles.yaml
      Parameters:
        Environment: !Ref Environment
        GitHubOrg: !Ref GitHubOrg
        GitHubRepo: !Ref GitHubRepo

  ECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecr.yaml
      Parameters:
        Environment: !Ref Environment

  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityGroupsStack
    Properties:
      TemplateURL: ./alb.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        ALBSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroupId
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref DomainName

  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityGroupsStack
      - IAMRolesStack
      - ECRStack
      - ALBStack
      - AuroraStack
      - SecretsManagerStack
    Properties:
      TemplateURL: ./ecs-cluster.yaml
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        ECSSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.ECSSecurityGroupId
        ECSTaskExecutionRoleArn: !GetAtt IAMRolesStack.Outputs.ECSTaskExecutionRoleArn
        ECSTaskRoleArn: !GetAtt IAMRolesStack.Outputs.ECSTaskRoleArn
        BackendRepositoryUri: !GetAtt ECRStack.Outputs.BackendRepositoryUri
        FrontendRepositoryUri: !GetAtt ECRStack.Outputs.FrontendRepositoryUri
        BackendImageTag: !Ref BackendImageTag
        FrontendImageTag: !Ref FrontendImageTag
        BackendTargetGroupBlueArn: !GetAtt ALBStack.Outputs.BackendTargetGroupBlueArn
        FrontendTargetGroupBlueArn: !GetAtt ALBStack.Outputs.FrontendTargetGroupBlueArn
        DatabaseCredentialsSecretArn: !GetAtt SecretsManagerStack.Outputs.DatabaseCredentialsSecretArn
        ApplicationSecretsArn: !GetAtt SecretsManagerStack.Outputs.ApplicationSecretsArn
        MinTaskCount: !Ref MinTaskCount
        MaxTaskCount: !Ref MaxTaskCount
        UseFargateSpot: !Ref UseFargateSpot
        SpotPercentage: !Ref SpotPercentage
        UseGraviton2: !Ref UseGraviton2

  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ECSClusterStack
      - ALBStack
      - IAMRolesStack
    Properties:
      TemplateURL: ./codedeploy.yaml
      Parameters:
        Environment: !Ref Environment
        ClusterName: !GetAtt ECSClusterStack.Outputs.ClusterName
        BackendServiceName: !GetAtt ECSClusterStack.Outputs.BackendServiceName
        FrontendServiceName: !GetAtt ECSClusterStack.Outputs.FrontendServiceName
        BackendTargetGroupBlueArn: !GetAtt ALBStack.Outputs.BackendTargetGroupBlueArn
        BackendTargetGroupGreenArn: !GetAtt ALBStack.Outputs.BackendTargetGroupGreenArn
        FrontendTargetGroupBlueArn: !GetAtt ALBStack.Outputs.FrontendTargetGroupBlueArn
        FrontendTargetGroupGreenArn: !GetAtt ALBStack.Outputs.FrontendTargetGroupGreenArn
        CodeDeployRoleArn: !GetAtt IAMRolesStack.Outputs.CodeDeployRoleArn
        DeploymentType: !Ref DeploymentType
        TrafficShiftPercentage: !Ref TrafficShiftPercentage

Conditions:
  ValidateAccount: !Equals [!Ref AWS::AccountId, !Ref AwsAccountId]
  HasGitHubOrg: !Not [!Equals [!Ref GitHubOrg, '']]

Outputs:
  LoadBalancerDNSName:
    Description: Application Load Balancer DNS name
    Value: !GetAtt ALBStack.Outputs.LoadBalancerDNSName
    Export:
      Name: !Sub '${AWS::StackName}-LoadBalancerDNSName'

  DBClusterEndpoint:
    Description: Aurora cluster endpoint
    Value: !GetAtt AuroraStack.Outputs.DBClusterEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-DBClusterEndpoint'

  ClusterName:
    Description: ECS cluster name
    Value: !GetAtt ECSClusterStack.Outputs.ClusterName
    Export:
      Name: !Sub '${AWS::StackName}-ClusterName'

  BackendServiceName:
    Description: Backend service name
    Value: !GetAtt ECSClusterStack.Outputs.BackendServiceName
    Export:
      Name: !Sub '${AWS::StackName}-BackendServiceName'

  FrontendServiceName:
    Description: Frontend service name
    Value: !GetAtt ECSClusterStack.Outputs.FrontendServiceName
    Export:
      Name: !Sub '${AWS::StackName}-FrontendServiceName'

  BackendCodeDeployApplicationName:
    Description: Backend CodeDeploy application name
    Value: !GetAtt CodeDeployStack.Outputs.BackendCodeDeployApplicationName
    Export:
      Name: !Sub '${AWS::StackName}-BackendCodeDeployApplicationName'

  FrontendCodeDeployApplicationName:
    Description: Frontend CodeDeploy application name
    Value: !GetAtt CodeDeployStack.Outputs.FrontendCodeDeployApplicationName
    Export:
      Name: !Sub '${AWS::StackName}-FrontendCodeDeployApplicationName'

  GitHubActionsRoleArn:
    Description: GitHub Actions Role ARN (if configured)
    Condition: HasGitHubOrg
    Value: !GetAtt IAMRolesStack.Outputs.GitHubActionsRoleArn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleArn'




