AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets Manager secrets for database credentials and application secrets'

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    AllowedValues:
      - staging
      - production
    Default: staging

  DatabaseName:
    Type: String
    Description: Database name
    Default: isms_db

  MasterUsername:
    Type: String
    Description: Master username for database
    Default: postgres
    NoEcho: true

Resources:
  DatabaseCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'isms-${Environment}-db-credentials'
      Description: Database credentials for Aurora PostgreSQL
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username":"${MasterUsername}","dbname":"${DatabaseName}"}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub 'isms-${Environment}-db-credentials'
        - Key: Environment
          Value: !Ref Environment

  ApplicationSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub 'isms-${Environment}-app-secrets'
      Description: Application secrets (JWT secrets, API keys, etc.)
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: trustCenterJwtSecret
        PasswordLength: 64
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub 'isms-${Environment}-app-secrets'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DatabaseCredentialsSecretArn:
    Description: ARN of database credentials secret
    Value: !Ref DatabaseCredentialsSecret
    Export:
      Name: !Sub '${AWS::StackName}-DatabaseCredentialsSecretArn'

  ApplicationSecretsArn:
    Description: ARN of application secrets
    Value: !Ref ApplicationSecrets
    Export:
      Name: !Sub '${AWS::StackName}-ApplicationSecretsArn'







